# Generated by Django 5.0.4 on 2024-05-11 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0003_remove_book_author_remove_book_genre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('book_title', models.CharField(max_length=50)),
                ('isbn_number', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='BookStore.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='BookStore.isbn'),
            preserve_default=False,
        ),
    ]
