# Generated by Django 5.0.4 on 2024-05-14 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0005_remove_book_isbn_remove_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(50)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
